# -*- coding: utf-8 -*-
"""LLM Assignment 2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BuI-xJYMHiUPSQw5MFYLaBgVLHO9YQML
"""

# ============================================================
# CELL 1: Install the Anthropic library
# Run this cell first. It installs the Claude API client.
# ============================================================

!pip install anthropic

# ============================================================
# CELL 2: Setup (Groq version — no Anthropic needed)
# ============================================================

# Nothing to configure here — Groq client is set up in Cell 4
print("✅ Ready! Groq will be configured in Cell 4.")

# ============================================================
# CELL 3: Define prompts for the 3 modes
# Each mode wraps the user's input with a different instruction
# This is the core of "prompt design" (Task 3)
# ============================================================

def get_prompt(mode, user_input):
    """
    Returns a mode-specific prompt string.

    Modes:
      1. summarization  - Condenses the text into key points
      2. explanation    - Explains the text in simple terms
      3. insight        - Extracts key insights or analysis
    """

    if mode == "summarization":
        # Mode 1: Ask the LLM to summarize
        return f"Summarize the following text in a few clear bullet points:\n\n{user_input}"

    elif mode == "explanation":
        # Mode 2: Ask the LLM to explain simply
        return f"Explain this in simple terms, as if talking to a beginner:\n\n{user_input}"

    elif mode == "insight":
        # Mode 3: Ask the LLM for analysis/insights
        return f"Give key insights and analysis from the following:\n\n{user_input}"

    else:
        # Fallback if an unrecognized mode is passed
        return f"Respond to the following:\n\n{user_input}"

print("✅ Prompt functions defined!")

# ============================================================
# CELL 4: Use Groq API instead of Anthropic
# Groq is free and very fast!
# Your secret key name in Colab: GROQ_API_KEY
# ============================================================

!pip install -q groq

from groq import Groq
from google.colab import userdata

# Load GROQ API key from Colab Secrets
# Make sure you added it as: GROQ_API_KEY in the 🔑 secrets panel
try:
    GROQ_KEY = userdata.get('GROQ_API_KEY')
    print("✅ Groq key loaded from Colab Secrets!")
except:
    GROQ_KEY = "paste-your-groq-key-here"  # ← fallback if secrets not set
    print("⚠️  Using hardcoded key.")

# Create the Groq client
groq_client = Groq(api_key=GROQ_KEY)

def query_llm(prompt):
    """
    Sends a prompt to Groq (LLaMA model) and returns the response.
    Drop-in replacement for the Anthropic version.
    All other cells work without any changes.
    """
    response = groq_client.chat.completions.create(
       model="llama-3.3-70b-versatile",   # current supported model
        messages=[
            {"role": "user", "content": prompt}
        ],
        max_tokens=1024
    )
    return response.choices[0].message.content

print("✅ Groq LLM function ready!")

# ============================================================
# CELL 5: Main interactive program
# Takes user input, lets them pick a mode, and shows output.
# This combines Tasks 1, 2, and 4.
# ============================================================

def run_llm_program():
    """
    Interactive loop:
    1. Ask the user for input text
    2. Ask which mode they want
    3. Build the prompt and call the LLM
    4. Display the result
    """

    print("=" * 50)
    print("       🤖 LLM Multi-Mode Assistant")
    print("=" * 50)

    # Step 1: Get user input
    user_input = input("\n📝 Enter your text or query:\n> ")

    # Step 2: Pick a mode
    print("\n🎛️  Choose a mode:")
    print("  1. Summarization")
    print("  2. Explanation")
    print("  3. Insight / Analysis")

    mode_choice = input("\nEnter 1, 2, or 3: ").strip()

    # Map number to mode name
    mode_map = {
        "1": "summarization",
        "2": "explanation",
        "3": "insight"
    }

    mode = mode_map.get(mode_choice, "summarization")  # Default to summarization

    # Step 3: Build the prompt using the selected mode
    prompt = get_prompt(mode, user_input)

    print(f"\n⏳ Sending to Claude in [{mode.upper()}] mode...\n")

    # Step 4: Query the LLM and display the response
    response = query_llm(prompt)

    print("=" * 50)
    print(f"📤 Response ({mode.upper()} mode):")
    print("=" * 50)
    print(response)

# Run the program
run_llm_program()

# ============================================================
# CELL 6: TASK 5 — Prompt Experimentation
# Try 3 different prompt styles on the SAME input.
# Observe how the output changes based on wording alone.
# ============================================================

# Use a fixed sample input so results are comparable
sample_input = "Artificial intelligence is transforming industries by automating tasks, improving decision-making, and enabling new capabilities in healthcare, finance, and education."

# Define 3 different prompt variations for the same task
prompt_variants = [
    # Variant A: Very direct and brief
    f"Summarize: {sample_input}",

    # Variant B: Instructional with structure
    f"Summarize the following text in exactly 2 sentences:\n\n{sample_input}",

    # Variant C: Role-based prompt (persona)
    f"You are a journalist writing for a general audience. Summarize this in one clear sentence:\n\n{sample_input}"
]

labels = [
    "Variant A — Short Direct Prompt",
    "Variant B — Structured with Constraints",
    "Variant C — Role-Based Persona Prompt"
]

print("🔬 PROMPT EXPERIMENTATION — Same Input, 3 Different Prompts\n")
print(f"📌 Input: {sample_input}\n")
print("=" * 60)

# Loop through each variant and display the LLM's response
for i, (label, prompt) in enumerate(zip(labels, prompt_variants)):
    print(f"\n🧪 {label}")
    print(f"   Prompt sent: \"{prompt[:80]}...\"")  # Show first 80 chars of prompt
    print(f"\n📤 Output:")

    response = query_llm(prompt)
    print(response)
    print("-" * 60)

# ============================================================
# CELL 7: TASK 6 — Understanding and Reflection
# This cell asks Claude to write a reflection on what we
# observed about prompt design across the experiments above.
# ============================================================

reflection_prompt = """
Write 5-6 lines explaining:
1. What changes when you modify the wording of a prompt given to an LLM
2. Why prompt design is critically important when working with large language models
Keep it clear and suitable for a beginner student learning about AI.
"""

print("💭 REFLECTION: Understanding Prompt Design\n")
print("=" * 60)

reflection = query_llm(reflection_prompt)
print(reflection)

print("\n" + "=" * 60)
print("✅ All 6 Tasks Complete!")
print("""
📚 Key Takeaway:
   The same LLM + same input → different output based purely
   on how you word the prompt. This is why prompt engineering
   matters — input → prompt → output is the full pipeline.
""")