# -*- coding: utf-8 -*-
"""Build an LLM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1elLa1pfRQ9LbLpzJdQC84niWRpxu7Mvm
"""

pip install langchain langchain-community transformers torch

import os
import torch
from langchain_core.prompts import PromptTemplate
from langchain_community.llms import HuggingFacePipeline
from transformers import pipeline, AutoTokenizer, AutoModelForCausalLM

print("🔄 Loading a MUCH smarter AI model... (This will take a minute)")

# 1. Using a smart, instruction-tuned model from Microsoft
model_id = "microsoft/Phi-3-mini-4k-instruct"
tokenizer = AutoTokenizer.from_pretrained(model_id)

# Load the model with optimizations for the GPU
model = AutoModelForCausalLM.from_pretrained(
    model_id,
    device_map="auto",
    torch_dtype=torch.float16
)

# Create the pipeline
hf_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=100,        # Give it enough room to write a full answer
    temperature=0.3,           # Low temperature makes it less random/crazy
    do_sample=True
)

llm = HuggingFacePipeline(pipeline=hf_pipeline)

# 2. A clean prompt template made for assistant models
template = """<|user|>
Answer this question clearly and concisely: {user_question}<|end|>
<|assistant|>"""

prompt = PromptTemplate.from_template(template)

# 3. Connect the pipes
chain = prompt | llm

print("\n🤖 Smart AI Assistant Ready! Type 'exit' to stop.")
print("-" * 50)

while True:
    user_input = input("\nYou: ")
    if user_input.lower() in ['exit', 'quit']:
        print("Goodbye!")
        break
    if not user_input.strip():
        continue

    print("Thinking...")
    response = chain.invoke({"user_question": user_input})

    # Clean up the output to show just the final answer
    clean_response = response.split("<|assistant|>")[-1].strip()
    print(f"\nAI: {clean_response}")