# -*- coding: utf-8 -*-
"""LLM 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YBAFjY7m7z94VhYU5HKbKP12vVuyor6O
"""

# Install Hugging Face Transformers and Datasets libraries
!pip install transformers datasets

import torch
from torch.utils.data import Dataset
from transformers import GPT2Tokenizer
from datasets import load_dataset

# 1. Load the tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
# Define a padding token since GPT2 doesn't have one by default
tokenizer.pad_token = tokenizer.eos_token

# 2. Build a custom Dataset class to process text file into 128-token chunks
class TextChunksDataset(Dataset):
    def __init__(self, file_path, tokenizer, max_length=128):
        self.examples = []
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()

        # Tokenize the full corpus
        tokenized_text = tokenizer.encode(text)

        # Chop text into fixed chunks of 128 tokens [00:13:13]
        for i in range(0, len(tokenized_text) - max_length + 1, max_length):
            self.examples.append(tokenized_text[i : i + max_length])

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        item = torch.tensor(self.examples[idx])
        return {"input_ids": item, "labels": item}

# 3. Download and prepare the WikiText dataset [00:13:51]
raw_dataset = load_dataset("wikitext", "wikitext-2-raw-v1")

# Save the raw text to a file for our custom data loader
with open("wiki_text.txt", "w", encoding="utf-8") as f:
    for text in raw_dataset["train"]["text"]:
        if text.strip():
            f.write(text + "\n")

# Instantiate the custom dataset
dataset = TextChunksDataset("wiki_text.txt", tokenizer, max_length=128)

from transformers import GPT2Config, GPT2LMHeadModel

# Create a smaller, lightweight version of GPT-2 [00:13:35]
# 6 hidden layers, 256 embedding dimensions (lightweight but a real transformer)
config = GPT2Config(
    vocab_size=len(tokenizer),
    n_positions=128,
    n_ctx=128,
    n_embd=256,
    n_layer=6,
    n_head=8
)

model = GPT2LMHeadModel(config)

import torch
from torch.utils.data import Dataset
from transformers import GPT2Tokenizer, GPT2Config, GPT2LMHeadModel, Trainer, TrainingArguments, pipeline
from datasets import load_dataset

# 1. Setup Tokenizer
tokenizer = GPT2Tokenizer.from_pretrained("gpt2")
tokenizer.pad_token = tokenizer.eos_token

# 2. Dataset Splitter
class TextChunksDataset(Dataset):
    def __init__(self, file_path, tokenizer, max_length=128):
        self.examples = []
        with open(file_path, "r", encoding="utf-8") as f:
            text = f.read()
        tokenized_text = tokenizer.encode(text)
        for i in range(0, len(tokenized_text) - max_length + 1, max_length):
            self.examples.append(tokenized_text[i : i + max_length])

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, idx):
        item = torch.tensor(self.examples[idx])
        return {"input_ids": item, "labels": item}

# 3. Download Wikipedia Text
raw_dataset = load_dataset("wikitext", "wikitext-2-raw-v1")
with open("wiki_text.txt", "w", encoding="utf-8") as f:
    for text in raw_dataset["train"]["text"]:
        if text.strip():
            f.write(text + "\n")

dataset = TextChunksDataset("wiki_text.txt", tokenizer, max_length=128)

# 4. Configure Small GPT-2 Model
config = GPT2Config(
    vocab_size=len(tokenizer),
    n_positions=128,
    n_ctx=128,
    n_embd=256,
    n_layer=6,
    n_head=8
)
model = GPT2LMHeadModel(config)

# 5. Train the Model (FIXED: removed overwrite_output_dir)
training_args = TrainingArguments(
    output_dir="./gpt2_scratch_results",
    num_train_epochs=1,
    per_device_train_batch_size=16,
    logging_steps=50,
    learning_rate=5e-4,
    fp16=True
)

trainer = Trainer(model=model, args=training_args, train_dataset=dataset)
trainer.train()

# 6. Test it!
generator = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)
print(generator("History of artificial intelligence", max_length=50)[0]['generated_text'])

from transformers import pipeline

# Load generation pipeline with our trained model
generator = pipeline("text-generation", model=model, tokenizer=tokenizer, device=0)

# Set generation constraints (max 100 tokens) [00:14:47]
prompt = "History of artificial intelligence"
output = generator(prompt, max_length=100, num_return_sequences=1)

print(output[0]['generated_text'])

# Install libraries required for efficient fine-tuning
!pip install transformers datasets peft bitsandbytes trl

from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import LoraConfig, get_peft_model

model_id = "facebook/opt-125m"  # 125M parameter model perfect for Colab [00:16:16]

tokenizer = AutoTokenizer.from_pretrained(model_id)
model = AutoModelForCausalLM.from_pretrained(model_id, device_map="auto")

# Configure LoRA [00:16:32]
# Freezes original weights, adds tiny trainable matrices to attention layers
peft_config = LoraConfig(
    r=8,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj"], # Targets target attention layers
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

# Wrap base model with LoRA configurations
model = get_peft_model(model, peft_config)

# Print trainable parameters (Will print out that only ~0.5% is being trained) [00:16:32]
model.print_trainable_parameters()

from datasets import load_dataset
from trl import SFTTrainer
from transformers import TrainingArguments

# Load the Databricks Dolly 15k instruction-following dataset [00:17:41]
dolly_dataset = load_dataset("databricks/databricks-dolly-15k", split="train")

# Formatting prompts cleanly to teach the model how to follow instructions [00:17:54]
def formatting_prompts_func(example):
    output_texts = []
    for i in range(len(example['instruction'])):
        text = f"### Instruction:\n{example['instruction'][i]}\n\n### Response:\n{example['response'][i]}"
        output_texts.append(text)
    return output_texts

# Define fine-tuning configuration [00:18:16]
training_args = TrainingArguments(
    output_dir="./opt_lora_results",
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-4,
    logging_steps=10,
    max_steps=100,               # Set small for demo, increase for deeper fine-tuning
    fp16=True
)

# Use Supervised Fine-Tuning (SFT) Trainer
trainer = SFTTrainer(
    model=model,
    train_dataset=dolly_dataset,
    peft_config=peft_config,
    formatting_func=formatting_prompts_func,
    data_collator=None,          # Handled natively by packing/formatting config
    args=training_args,
)

# Run the training process
trainer.train()

