# -*- coding: utf-8 -*-
"""ML 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_t6Q0eBERNm2fbOLrT0T7E_aeXykgPOe
"""

# Install the library that downloads stock data from NSE/BSE
!pip install yfinance

import yfinance as yf          # downloads stock prices
import pandas as pd            # works with tables (DataFrames)
import matplotlib.pyplot as plt  # draws charts

# We are using Reliance Industries from NSE
# NSE symbol = RELIANCE.NS
# BSE symbol would be RELIANCE.BO

stock = yf.download("RELIANCE.NS", period="1mo", interval="1d")

# Keep only the closing price column
stock = stock[["Close"]].copy()

# Rename for simplicity
stock.columns = ["Close"]

# Show the data
print(stock)
print("\nTotal days:", len(stock))

# ── STEP 2: Create target column ──────────────────────────────
# If tomorrow's price is higher than today → 1 (UP)
# If tomorrow's price is lower than today  → 0 (DOWN)

stock["Tomorrow"] = stock["Close"].shift(-1)        # next day's price
stock["Target"]   = (stock["Tomorrow"] > stock["Close"]).astype(int)

# ── STEP 3: Create features ───────────────────────────────────

# Feature 1: Daily % change (did price go up or down TODAY?)
stock["Daily_Change"] = stock["Close"].pct_change() * 100

# Feature 2: 3-day moving average (smooth average of last 3 days)
stock["MA3"] = stock["Close"].rolling(window=3).mean()

# Feature 3: Is today's price above the moving average?
# 1 = above (bullish), 0 = below (bearish)
stock["Above_MA"] = (stock["Close"] > stock["MA3"]).astype(int)

# Drop rows that have missing values (first few rows won't have MA3)
stock = stock.dropna()

# Show final table
print(stock[["Close", "Daily_Change", "MA3", "Above_MA", "Target"]])

# ── STEP 2: Create target column ──────────────────────────────
# If tomorrow's price is higher than today → 1 (UP)
# If tomorrow's price is lower than today  → 0 (DOWN)

stock["Tomorrow"] = stock["Close"].shift(-1)        # next day's price
stock["Target"]   = (stock["Tomorrow"] > stock["Close"]).astype(int)

# ── STEP 3: Create features ───────────────────────────────────

# Feature 1: Daily % change (did price go up or down TODAY?)
stock["Daily_Change"] = stock["Close"].pct_change() * 100

# Feature 2: 3-day moving average (smooth average of last 3 days)
stock["MA3"] = stock["Close"].rolling(window=3).mean()

# Feature 3: Is today's price above the moving average?
# 1 = above (bullish), 0 = below (bearish)
stock["Above_MA"] = (stock["Close"] > stock["MA3"]).astype(int)

# Drop rows that have missing values (first few rows won't have MA3)
stock = stock.dropna()

# Show final table
print(stock[["Close", "Daily_Change", "MA3", "Above_MA", "Target"]])

# ── STEP 4: Define the model rules ────────────────────────────

def my_model(row):
    # Rule 1: Price above MA and rising → UP
    if row["Above_MA"] == 1 and row["Daily_Change"] > 0:
        return 1
    # Rule 2: Price below MA and falling → DOWN
    elif row["Above_MA"] == 0 and row["Daily_Change"] < 0:
        return 0
    # Rule 3: Mixed signals → follow daily change
    else:
        if row["Daily_Change"] > 0:
            return 1
        else:
            return 0

# ── STEP 5: Apply your model to every row ─────────────────────

stock["Predicted"] = stock.apply(my_model, axis=1)

result = stock[["Close", "Daily_Change", "MA3", "Above_MA", "Predicted", "Target"]].copy()
result["Correct"] = (result["Predicted"] == result["Target"])

print(result)

# ── STEP 6: Calculate accuracy ────────────────────────────────

correct     = result["Correct"].sum()       # number of correct predictions
total       = len(result)                   # total predictions made
accuracy    = (correct / total) * 100       # accuracy in %

print(f"Correct predictions : {correct} / {total}")
print(f"Accuracy            : {accuracy:.1f}%")
print()

# Count how many UP and DOWN calls were correct
up_correct   = result[(result["Target"]==1) & (result["Predicted"]==1)].shape[0]
down_correct = result[(result["Target"]==0) & (result["Predicted"]==0)].shape[0]
print(f"UP predictions correct   : {up_correct}")
print(f"DOWN predictions correct : {down_correct}")

# ── Chart ─────────────────────────────────────────────────────
plt.figure(figsize=(12, 4))

plt.plot(result.index, result["Target"],    label="Actual",    marker="o", color="green")
plt.plot(result.index, result["Predicted"], label="Predicted", marker="x", color="blue", linestyle="--")

plt.title(f"Predicted vs Actual — Accuracy: {accuracy:.1f}%")
plt.xlabel("Date")
plt.ylabel("0 = DOWN,  1 = UP")
plt.yticks([0, 1], ["DOWN (0)", "UP (1)"])
plt.legend()
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

# ── STEP 7: Understand your results ───────────────────────────

print("=" * 45)
print("ANALYSIS OF YOUR MODEL")
print("=" * 45)

print(f"\nAccuracy: {accuracy:.1f}%")

if accuracy >= 60:
    print("Result: Good! Your rules are beating random chance (50%).")
else:
    print("Result: Below 60%. Rules need improvement.")

print("\nWHAT WORKED:")
print("  - Moving average crossover captures trend direction")
print("  - Daily momentum (% change) is a useful signal")

print("\nWHERE IT FAILED:")
print("  - Flat/sideways days are hard to classify")
print("  - Only 3 features = limited information")
print("  - No volume data used")
print("  - Rules are fixed; they don't learn from mistakes")

print("\nWHAT TO IMPROVE:")
print("  - Add a 5-day moving average (5-day MA)")
print("  - Add RSI indicator (measures overbought/oversold)")
print("  - Use a Decision Tree — it finds better rules automatically")
print("  - Try Logistic Regression — converts features to probability")

print("\nNEXT STEP:")
print("  Once you're comfortable, replace my_model() with:")
print("  from sklearn.tree import DecisionTreeClassifier")
print("  and let the algorithm learn the rules from your data!")