# -*- coding: utf-8 -*-
"""learning_ml_gradient descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mE_9SAarpYTxVBZCcOftxVqHRyObGHIh
"""

import numpy as np
import matplotlib.pyplot as plt

# ── Step 1: Create simple fake data ────────────────────────────
# House sizes (in hundreds of sq ft)
X = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10], dtype=float)
# House prices (in lakhs)
y = np.array([2, 4, 5, 4, 5, 7, 8, 9, 10, 12], dtype=float)

# ── Step 2: Initialize parameters randomly ──────────────────────
w = 0.0          # weight (slope)
b = 0.0          # bias (intercept)
learning_rate = 0.01
n = len(X)       # number of data points

# ── Step 3: Training loop (Gradient Descent) ────────────────────
for epoch in range(1000):
    # 3a. Forward pass: make predictions
    y_pred = w * X + b

    # 3b. Calculate loss (Mean Squared Error)
    loss = (1/n) * np.sum((y_pred - y)**2)

    # 3c. Calculate gradients
    dw = (2/n) * np.sum((y_pred - y) * X)   # d(loss)/d(w)
    db = (2/n) * np.sum(y_pred - y)          # d(loss)/d(b)

    # 3d. Update parameters
    w = w - learning_rate * dw
    b = b - learning_rate * db

    # Print every 100 epochs
    if epoch % 100 == 0:
        print(f'Epoch {epoch:4d} | Loss: {loss:.4f} | w={w:.3f}, b={b:.3f}')

# ── Step 4: Plot results ─────────────────────────────────────────
plt.scatter(X, y, color='blue', label='Actual Prices')
plt.plot(X, w*X + b, color='red', label='Predicted Line')
plt.xlabel('House Size (100 sq ft)')
plt.ylabel('Price (Lakhs)')
plt.title('Linear Regression via Gradient Descent')
plt.legend()
plt.show()

print(f'\nFinal: w = {w:.3f}, b = {b:.3f}')
print(f'Prediction for size=11: {w*11 + b:.2f} Lakhs')