# -*- coding: utf-8 -*-
"""ML Gradient Descent Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uCKEQL1nwd20QTJQonveutUSaFhgriu
"""

# ============================================================
# ML Assignment: Manual Decision Boundary vs SVM
# ============================================================

# Install/import all the libraries we need
import numpy as np
import matplotlib.pyplot as plt
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

# ============================================================
# STEP 1: CREATE DATASET
# We manually create 12 data points with two features:
#   - price_change: how much the stock price changed (%)
#   - volume_change: how much the trading volume changed (%)
# Labels: 1 = Buy, 0 = Sell
# ============================================================

# Each row is one data point: [price_change, volume_change]
data = np.array([
    [2.5,  3.0],   # price up, volume up   → likely Buy
    [3.1,  4.5],
    [1.8,  2.2],
    [4.0,  5.0],
    [2.0,  3.5],
    [0.5,  1.0],
    [-1.0, -2.0],  # price down, volume down → likely Sell
    [-2.5, -3.5],
    [-3.0, -4.0],
    [-1.5, -1.0],
    [-2.0, -3.0],
    [-0.5, -1.5],
])

# Labels for each data point (1=Buy, 0=Sell)
labels = np.array([1, 1, 1, 1, 1, 1,   # first 6 are Buy
                   0, 0, 0, 0, 0, 0])   # last 6 are Sell

# Split into features X and target y
X = data
y = labels

print("Dataset created!")
print(f"Total points: {len(X)}")
print(f"Buy points (1): {sum(y==1)}, Sell points (0): {sum(y==0)}")


# ============================================================
# STEP 2: VISUALIZATION — Plot the dataset
# Blue dots = Buy (1), Red dots = Sell (0)
# ============================================================

plt.figure(figsize=(7, 5))

# Plot Buy points
plt.scatter(X[y==1, 0], X[y==1, 1], color='blue', label='Buy (1)', s=80)

# Plot Sell points
plt.scatter(X[y==0, 0], X[y==0, 1], color='red', label='Sell (0)', s=80)

plt.xlabel("Price Change (%)")
plt.ylabel("Volume Change (%)")
plt.title("Step 2: Dataset Visualization")
plt.legend()
plt.grid(True)
plt.axhline(0, color='gray', linewidth=0.5)
plt.axvline(0, color='gray', linewidth=0.5)
plt.show()

print("Observation: Blue (Buy) points are in the top-right, Red (Sell) are in the bottom-left.")
print("They seem linearly separable — a straight line can separate them!")


# ============================================================
# STEP 3: MANUAL DECISION BOUNDARY
# We try to draw a line manually to separate Buy and Sell.
# A line is defined as: y = m*x + c
# We pick m=1.0 and c=0.2 based on visual inspection.
# ============================================================

# Our manually chosen line: y = 1.0 * x + 0.2
m_manual = 1.0   # slope
c_manual = 0.2   # intercept

# Generate x values to draw the line
x_line = np.linspace(-4, 5, 100)
y_line_manual = m_manual * x_line + c_manual

# Plot again with our manual line
plt.figure(figsize=(7, 5))
plt.scatter(X[y==1, 0], X[y==1, 1], color='blue', label='Buy (1)', s=80)
plt.scatter(X[y==0, 0], X[y==0, 1], color='red', label='Sell (0)', s=80)
plt.plot(x_line, y_line_manual, color='green', linewidth=2, label=f'Manual Line: y = {m_manual}x + {c_manual}')

plt.xlabel("Price Change (%)")
plt.ylabel("Volume Change (%)")
plt.title("Step 3: Manual Decision Boundary")
plt.legend()
plt.grid(True)
plt.show()

# Check how well our manual line classifies the points
# If a point is ABOVE the line → predict Buy (1), else Sell (0)
manual_predictions = []
for i in range(len(X)):
    x_val = X[i, 0]
    y_val = X[i, 1]
    line_y = m_manual * x_val + c_manual   # y-value on the line at this x
    if y_val > line_y:
        manual_predictions.append(1)  # point is above the line → Buy
    else:
        manual_predictions.append(0)  # point is below the line → Sell

manual_acc = accuracy_score(y, manual_predictions)
print(f"\nManual boundary accuracy: {manual_acc * 100:.1f}%")


# ============================================================
# STEP 4: GRADIENT DESCENT UNDERSTANDING
# We try different values of slope (m) and intercept (c)
# to see how the line changes. This mimics what gradient
# descent does — it adjusts m and c step by step to find
# the best boundary.
# ============================================================

print("\n--- Step 4: Trying different m and c values ---")

# Different combinations of m (slope) and c (intercept) to try
#VERY IMPORTANT - KEEP IN MIND
attempts = [
    (0.5,  0.0, "Attempt 1: low slope"),
    (1.0,  0.5, "Attempt 2: medium slope"),
    (1.2,  0.2, "Attempt 3: steeper slope"),
    (1.5, -0.5, "Attempt 4: steep, shifted down"),
]

plt.figure(figsize=(10, 8))

for idx, (m, c, label) in enumerate(attempts):
    plt.subplot(2, 2, idx + 1)

    # Plot data
    plt.scatter(X[y==1, 0], X[y==1, 1], color='blue', label='Buy', s=60)
    plt.scatter(X[y==0, 0], X[y==0, 1], color='red', label='Sell', s=60)

    # Draw this attempt's line
    y_line = m * x_line + c
    plt.plot(x_line, y_line, color='purple', linewidth=2)

    # Calculate accuracy of this line
    preds = []
    for i in range(len(X)):
        if X[i, 1] > m * X[i, 0] + c:
            preds.append(1)
        else:
            preds.append(0)
    acc = accuracy_score(y, preds)

    plt.title(f"{label}\nm={m}, c={c} | Acc={acc*100:.0f}%")
    plt.xlabel("Price Change")
    plt.ylabel("Volume Change")
    plt.grid(True)
    plt.ylim(-6, 7)

plt.suptitle("Step 4: Gradient Descent — Trying Different m and c", fontsize=12)
plt.tight_layout()
plt.show()

print("Notice: As we adjust m and c, the accuracy changes.")
print("Gradient descent does this automatically using math to find the best values!")


# ============================================================
# STEP 5: APPLY SVM
# Now we use Scikit-learn's SVM to find the OPTIMAL boundary.
# SVM finds the line that has the maximum margin (gap) between
# the two classes — much more reliable than guessing!
# ============================================================

# Train the SVM model
# kernel='linear' means we want a straight-line boundary
svm_model = SVC(kernel='linear')
svm_model.fit(X, y)   # SVM learns from the data

# Check accuracy
svm_predictions = svm_model.predict(X)
svm_acc = accuracy_score(y, svm_predictions)
print(f"\nSVM Accuracy: {svm_acc * 100:.1f}%")

# --- Plot SVM Decision Boundary ---
# To draw the SVM boundary, we need to know the line equation.
# SVM gives us weights (w) and bias (b): w[0]*x + w[1]*y + b = 0
# Rearranging: y = -(w[0]/w[1])*x - (b/w[1])

w = svm_model.coef_[0]       # weights
b = svm_model.intercept_[0]  # bias

# SVM decision boundary line
x_svm = np.linspace(-4, 5, 100)
y_svm = -(w[0] / w[1]) * x_svm - (b / w[1])

# SVM also gives us margin lines (support vectors)
# Upper margin: + 1/w[1]
# Lower margin: - 1/w[1]
y_svm_upper = y_svm + 1 / w[1]
y_svm_lower = y_svm - 1 / w[1]

plt.figure(figsize=(8, 6))

# Plot data
plt.scatter(X[y==1, 0], X[y==1, 1], color='blue', label='Buy (1)', s=80, zorder=3)
plt.scatter(X[y==0, 0], X[y==0, 1], color='red', label='Sell (0)', s=80, zorder=3)

# Highlight support vectors (the closest points to the boundary)
plt.scatter(svm_model.support_vectors_[:, 0],
            svm_model.support_vectors_[:, 1],
            s=150, facecolors='none', edgecolors='black',
            linewidths=2, label='Support Vectors', zorder=4)

# Draw manual boundary (green)
plt.plot(x_line, y_line_manual, color='green', linewidth=2,
         linestyle='--', label=f'Manual (m={m_manual}, c={c_manual})')

# Draw SVM boundary and margins (orange)
plt.plot(x_svm, y_svm, color='orange', linewidth=2.5, label='SVM Boundary')
plt.plot(x_svm, y_svm_upper, color='orange', linewidth=1.5, linestyle=':', label='SVM Margin')
plt.plot(x_svm, y_svm_lower, color='orange', linewidth=1.5, linestyle=':')

plt.xlabel("Price Change (%)")
plt.ylabel("Volume Change (%)")
plt.title("Step 5: SVM Decision Boundary vs Manual Boundary")
plt.legend()
plt.grid(True)
plt.ylim(-6, 7)
plt.show()

print("✅ Assignment Complete!")